/* 
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/Other/SQLTemplate.sql to edit this template
 */
/**
 * Author:  Coder
 * Created: 15/10/2025
 */

-- MySQL Script generated by MySQL Workbench
-- mar 14 oct 2025 14:16:52
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema booknova
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `booknova` ;

-- -----------------------------------------------------
-- Schema booknova
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `booknova` ;
USE `booknova` ;

-- -----------------------------------------------------
-- Table `booknova`.`books`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booknova`.`books` ;

CREATE TABLE IF NOT EXISTS `booknova`.`books` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `isbn` VARCHAR(100) NOT NULL,
  `title` VARCHAR(45) NOT NULL,
  `author` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `total_copies` INT NOT NULL,
  `reference_price` DECIMAL(10,2) NULL,
  `is_activo` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `isbn_UNIQUE` (`isbn` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknova`.`users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booknova`.`users` ;

CREATE TABLE IF NOT EXISTS `booknova`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `rol` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `password` VARCHAR(250) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknova`.`partners`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booknova`.`partners` ;

CREATE TABLE IF NOT EXISTS `booknova`.`partners` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `status` VARCHAR(45) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `update_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `booknova`.`loans`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `booknova`.`loans` ;

CREATE TABLE IF NOT EXISTS `booknova`.`loans` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `id_book` INT NOT NULL,
  `id_partners` INT NOT NULL,
  `issue_loan` DATE NOT NULL,
  `return_date` DATE NOT NULL,
  `fine` VARCHAR(45) NULL,
  `is_devuelto` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `id_book_idx` (`id_book` ASC) VISIBLE,
  INDEX `id_partners_idx` (`id_partners` ASC) VISIBLE,
  CONSTRAINT `id_book`
    FOREIGN KEY (`id_book`)
    REFERENCES `booknova`.`books` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `id_partners`
    FOREIGN KEY (`id_partners`)
    REFERENCES `booknova`.`partners` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
